version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py  # Update with your Flask app entry point
      FLASK_ENV: development


volumes:
  postgres_data: